stages:
  - tests
  - dev

tests:
  stage: tests
  image: binkhq/python:3.8
  script:
  - mkdir -p /root/.ssh
  - chown 700 /root/.ssh
  - echo "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS0FJQkFBS0NBZ0VBdUhJbnpDRFNKeWQ4UEpTRy8vZmVQQ0gybThmVVFLRVJJOXYyT202Tk5KQml0eTkyClVLaHQzUHUxUDVRMmE3QzdKc2R0ZkNZL2FMeEY0ZFBFY2wzWnd0TkQ5eDBEQXJtemF5c0FvMUxrYXllMWxCVjcKOWNReEpoSjVYNnFiZktYeTY5azZ4ZldhamdWcTZKbWpnQmR4bXllNVFEaXBoZVZadVZGd0x6MlE0SVlySThTUApEZDZ0cnBpOU9sTW1nMDJRaERYTmxjVHkvdHFUUmRJYzhvelJBR3NUdEJUZUNRRlJhUHpFOW9jdDcvYTI5ZElZCjY5ZVc4Wkg0RDR0WlpTZXlkRnVTa3N4VGJKTUNZNHFIbDVqVlE4Nys0VFRzYXRwVEJKS1hpWVI4d3hHRGpQVTgKeEQzMzZDa3hqeTloU3p1SGljVzJOdW1hWE5YVTNWeTZqN3BiNVFaK0RRdHBPQmJXclVkdVF3dUI4bEdUbDZ6agpoRjVHd0RYT3BOa0x4d2oyazA5cGgwQ3lPM3lENGJnMWlEZC9oTFEvbE1HOHVhdHhKZS9zZXRYR05FSEVEaEFvCjRudUxZSi9JOFcrRWZ3TVRQRG1TVWg1V1JSRWFFLy9abmFsWWZXTkNRL1hDa2FzS2xvZEJrcmVSSXllTzRBSncKTWhyZ09YSi82bzRxUTR6YlZOWVBOTXlYdjdEQzNxaWZPRlJVOFVPVXNtVUlrYnMrcVJPQkwvc0ZNQjJHK3c4cwpJUHBJY0pLSVVpMFNKdXVCMTRUdWRveHd5QkxVNVJTTXU4NmxyM0NYR245ZEJpWWphTFdkNTdyQStxcTlwWmVZClVBTi9Mem52ZUoxOXVqZEVQdXkwYVUrUWVJME9wcG1kdVp1NkNHOVhmQXBmdFhRZndXa1N2dVdJbGFzQ0F3RUEKQVFLQ0FnQVFSL3RkV0hSVWduYkQvalJnZWVmREZSaG9yZDM5aW5veDJTUEdDcVlxUXFpRUZRdHptVHFCYkRLVwpseVdxb2VJVFRUMUwzVEJ4dFZUUjExaWE0OC9xRTY0SExTZHI0U3FHUmpoN01rRDVlSHJkeEh1NXVRVEJvSlhZCkxQNG1wWnRvMkRjSTdHSWxNVE03cnZ3d3ZXRUkyaHZQSUhGT1lXMW5IMW93d1ZWOWpEcFlvT3dqeEVrK2hUc0cKMy9vaFV3Snp1VEFaalZZSnl3OSs5VW9hMnZWRC9TK3pFTGg4d1FJSHEzQlRkcUZHY2xlNklUNlQ2dWJuRWdSOAprc2RrVjNtNExiRWxoaVhEQ3NNR09GODVzWUw1eGxiWFdFMmFMUVZ3L09PbGZ1MW9acTVmRGZLOE8rQWJQUytqCnZRSHdteU9ldExZZDZNYjRkT09pV3FJWk45RU9vcnRITEUvYmhLSDdrbk5MRzdvUzgxdlp5TW5HcTJwblFQK3cKREJPbThPYzNSZ3MyQVpiVFhsVHNYNW9WNkFlM3BVY3lKY281blRTQW5MKzZRMjVmNlFUUGpSMXBpZkxpdC80TQozTmFVM3UrVlBqTXMyTmdBNzVXcHhzYUt2OHBUVkV4QnNnZEZFcGFZTnBHTDhXcUJTWU5JRWhkeE1CaC9lNENVCmlQSnBlMjJXN3hPYXdQWDIwcDdEUHFWK21LSE84by9yS3NuWE5oK3RPY1puWXg5cXdJbUg0OGZnMW5xYldDZDAKakE3SkorRzg0Y1VFR2prVU80cko2S0drcTllM0JYNEMxYm9zQ3Fnd2lPN1FTc3Vqcndxd2pjSGcyMndmbjNZVQpndG9XTGNtVm5MR1o5Q1RQRi9KYXhobFRQQ0U2aWp4WXdqL1Z5RmcxZ1FUblNDZEptUUtDQVFFQTlYT05YMGxLCkVHTDIzazhZM0ZGNVhuT0hoeWF1WDl3MktnYmMxc0FXU0JPMVQ0VGp5VDl4cUsvTG1YRjZ6QTgxWGl1UW5mcEUKV0tDUW93SXFwVFVaVTZTbW4rRHVTbitoSXlTRzRsU0p4RE5oNUxIaGg2SDgwMmRhd2UrWlJVY0IzQ1RBWTJQcAo4WTdZT0poSzd6QVNRTTFyejF5NHdqVTUrRnkzMEk1NnZac1UvNjlra0hpaG9HY2xBMURVUnppZkhVSzJpK2F1CjhremVzb2xobDJ4V1VMVk1EOGM2T0VzdzI2WDB2U3dyeU5vWDNuM3FjN2J6SEhWWmkwR1JzRFFLb3lXN3Z4b0kKY3VKQzVOQy9ucXJGNEsxekxieFRhODcxYXJvZVVHaS9nMWI3VHFvVjJEQ1JxNGR0NEoyYTIxbkl1VXJxTFlLWQp4ekdGRWNncEZhT00vd0tDQVFFQXdGOXNXaXNBR2t5Vm1iZUFRUnArU1B2UVpVMnlyQVBZRnVQc2U3ek1lYUlICmxkZk5tb3hIbGZOaXlVdFBOOFRCL28zUytkWUxVZXl4Q1JzSTJRMDN6ejh5UUNMWGFWeEIvaGMybXFvbTFHSVUKWm5oOUo5QjdENXJiQ0FBcUZFY254bE4xT0t2MXFNVk10RVo4aUlETzRFVUkzdmxPK1JqRE5KSHFmMWtJYUVYRAowQkVOTzk1WGJ2R29nSC94Vit4cUI1SWVFWGNkcjduQVp1b0pXcXF3cGJ0Uk5vcjVycFpJQzE3eTJzd2d6eEUyClpxMHR2V3piV2Z3QVkyT2ZhUlNobTIrc2p1dURxT09pU3NvdWl5bko3eFlEQ3k4eXZuK2lmQkpEQndFRkp1ZXIKcjhhdUJKZ3VMcTg4ODJqRElRQ3RxR0ZRTmNqakk3UlE2SUoyYjBRN1ZRS0NBUUJpVmJqOXc4NzRZYTJsd3VxaQoyY0ZXSmRMV1FwajVycS9FaHB0VExnRy9QcVlWQlpoOHQvNUJKcXphL0t2RnRSSWNlRGVvRXV2dTFlVWNhWEhNClhrbVhTUSs0WGRVWjQ2Z2EvRGROMWJDYitqbnQ5WlgxVU9DSmtZNjZ3OU1UL2k2d2s4akFDUGRnMzJtZ3d1TEMKa08rL0pvMWF0anNQRTJQMkxLODN6dDA5dVRQZ2U5UStUUlh6dlY4R3hRdEd2VmlCMEloeDVDbVN5Vmt2RGZzYgpQendWZVl6UGhYRzl1K0lISGFXL1pFTG1aUG5MR1lja2ROZFJQM0p3YUFTR0kxTmZxVzVlVVgreEJ4VGx0dndPCkJUemhscHZlWnVURS9GVTJQUHFJSEc4ZG4ydHZTSlVYMTkyRWF1MktYNW42NXkyVGpuL2pXNzc1anMxUkltL1QKUzRMaEFvSUJBUUNHL3Ura1h1U1ZrQVN6ZUVneVo0c1RZRktmcEdTcnZZN1lrVjJVZjZybCtFUm1iS2hGdWdkSwpQUitucm9lSzFUSmxsZFRscWNVTDJwTnBsbVVoRzl0OFBoYmZWeFBmUmZTeGdFeTdRSWc3SmhDMnovclVBOE0zCjhpMmVjYThWeDlFcnBjbHUyWTFzdi9mUjBsejExWjVYVjFxZ1RrZVRHa055RXF1Q2JsSXVDamNkUGJvUnR6ZVkKRFZGM3kxRHJxR1hIcGt3ZmFYMlZvVDVaZWdiU2IxSERHNjRrSG1hVWs3VSs5WVJxOGpCYjN2SlVIMWNueE1veApYVnhRWXNxdERPTlRsb3g3UnQ1L21DNTlXV0JNSENrdTlEMXlqYzZJVEQwVDRDVFZOMndNSHlzbUVNQnhUUEdyCnBTR2FsbnZJSHhlK1AzdndJbWJ5MlVpbHdWZW5RVFI1QW9JQkFCTnp2VkdMOGhTVmgrVWszelZxVmFyUGp3Y0QKT3UvWW5hUnZYQXplZzcvVU1mbGF0UkpTOEpvUjRsSFM2WFBLMjROVEtPWXFVSVRsL2ZscFV5NS9Bdm1jU25RQgoxTUFnR2dRbXZMR0JCaUF2TW0zSWhHdUpsRnNrWUFPdXRmK090LzA3RVNsem1idFhFQUdZaW1tdHdVMDlBSU1WCmp3L2d0cHpjNWZET0swempUUDB6NTU0RjVIZjN6QzJKUnZJTlNHWnF2dGJsMnJIa0RmeGl3R1RzVW9pZ2F6dzgKaGJTQmkxbVNPTEFqdmtRRjZ2bmJMMmVta2d4Wm9hUHU2VGNKaHRTT25EVGJDSUJDMTVFOVE2bUNOUzBIMXFSSApnMXVKZUkwT2NLMWdNMEhIUVZYaURwWEFCbGdNNWR2NkE1eXZkTll3VVZLNnVjUzhDQVdyQy95b1pxST0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0KCg=="  | base64 --decode > /root/.ssh/id_rsa
  - chown 600 /root/.ssh/id_rsa
  - apt update && apt -y install git
  - ssh-keyscan -H git.bink.com >> /root/.ssh/known_hosts
  - export LC_ALL=C.UTF-8
  - export LANG=C.UTF-8
  - pip install pipenv
  - pipenv install --dev
  - pipenv run pytest app/tests --cov=app

complexity:
  stage: tests
  image: binkhq/python:3.8
  script:
    - pip install xenon flake8_polyfill
    - xenon --max-average A --max-modules B --max-absolute B .

style:
  stage: tests
  image: binkhq/python:3.8
  script:
    - pip install flake8
    - flake8

dev:
  stage: dev
  environment:
    name: dev
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - export CTAG="develop-$(date +%F-%H%M%S)"
    - docker build --pull -t "$CI_REGISTRY/selene:$CTAG" .
    - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock "$CI_REGISTRY/aqua-scanner:5.0" scan --local "$CI_REGISTRY/selene:$CTAG" --host https://aqua.uksouth.bink.sh:30001/ --user scanner --password $AQUA_PASSWORD --show-negligible --policies Bink --text
    - docker push "$CI_REGISTRY/selene:$CTAG"
  only:
    - develop
