tests:
  script:
  - pip3 install -r requirements.txt
  - py.test app/ --cov=app

  tags:
    - docker
  services:

complexity:
  script:
    - xenon --max-average A --max-modules B --max-absolute B .
  tags:
    - docker

flake8:
  script:
    - flake8 *
  tags:
    - docker

deploy:
  stage: deploy
  script:
    - docker build -t olympus.azurecr.io/selene:latest .
    - docker login olympus.azurecr.io -u $AZURE_LOGIN -p $AZURE_PASS
    - docker push olympus.azurecr.io/selene:latest
    - docker rmi olympus.azurecr.io/selene:latest
    - docker logout olympus.azurecr.io
  environment: dev
  only:
    - add_flask 
  tags:
    - shell

